### PR TITLE
Intake Update

### PR DESCRIPTION
**Pull request by z3ht**
Updated the intake project to allow for external modifications such as a Minecraft command gui. Changes are primarily located in the fluent API. The most notable changes for people using the Intake library surround how a BukkitIntake class is instantiated and the removal of @Group/@At/@Root annotations. The BukkitIntake class has been changed to allow for further modification. The listed annotations were removed because they provided a second, less expandable and more complicated way to do something that dispatcher nodes can already do.

### CODE REVIEW

**Review by Electroid — CHANGES_REQUESTED** [review]
I believe your IDE has made significant  changes to the formatting of the codebase. Can you isolate your actual changes from the formatting changes? This will make it easier to review.

**Comment by Electroid** [comment]
@z3ht If you add the `settings.xml` back in and change the `pom.xml` version to `1.1-SNAPSHOT` then we should be good to go.

**Comment by z3ht** [comment]
> @z3ht If you add the `settings.xml` back in and change the `pom.xml` version to `1.1-SNAPSHOT` then we should be good to go.

1) settings.xml is specific to the stratus network so shouldn't it be kept off of the master branch so other people can use the project without having to delete/modify that

2) I'll change the 'pom.xml' tomorrow

**Comment by Electroid** [comment]
This depends on SportPaper, is it possible to change the maven dependency to a more generic Bukkit version so it works for all Bukkit variants?

**Pull request closed without merging**
